name: 定时获取

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨2点运行
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch-and-generate-summary:
    runs-on: ubuntu-latest
    steps:
      - name: 发送请求到 Notion API
        uses: actionsflow/axios@v1
        id: fetch-notion
        with:
          url: https://api.notion.com/v1/databases/${{ secrets.DATABASE_ID }}/query
          method: POST
          headers: '{"Authorization": "Bearer ${{ secrets.NOTION_TOKEN }}", "Notion-Version": "2022-06-28", "Content-Type": "application/json"}'
          data: '{"filter": {"property": "Tags", "multi_select": {"contains": ""}}, "sorts": [{"property": "Created", "direction": "descending"}], "page_size": 1}'

      - name: 处理响应并生成
        if: success()
        id: generate-summary
        uses: actionsflow/axios@v1
        with:
          url: ${{ fromJson(steps.fetch-notion.outputs.response).results[0].properties.URL.url }}
          method: GET
          headers: '{"Authorization": "Bearer ${{ secrets.NOTION_TOKEN }}"}'

      - name: 输出 URL
        if: success()
        run: |
          location_header="${{ fromJson(steps.generate-summary.outputs.headers).location }}"
          if [ -n "$location_header" ]; then
            echo "URL: $location_header"
            echo "url=$location_header" >> $GITHUB_OUTPUT
          else
            echo "未能获取到 URL"
            echo "url=" >> $GITHUB_OUTPUT
          fi

      - name: 显示摘要 URL
        if: success() && steps.generate-summary.outputs.url != ''
        run: |
          echo "摘要 URL: ${{ steps.generate-summary.outputs.url }}"
