name: Scheduled Fetch

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨2点运行
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch-and-generate-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Notion API- 名称：向 Notion API 发送请求
        uses: actionsflow/axios@v1
        id: fetch-notion
        with:
          url: https://api.notion.com/v1/databases/${{ secrets.DATABASE_ID }}/query
          method: 'POST'
          accept: 200
          headers: |
            {
              "Authorization": "Bearer ${{ secrets.NOTION_TOKEN }}",
              "Notion-Version": "2022-06-28",
              "Content-Type": "application/json"
            }
          data: |
            {
              "filter": {
                "property": "Tags",
                "multi_select": {
                  "contains": ""
                }
              },
              "sorts": [
                {
                  "property": "Created",
                  "direction": "descending"
                }
              ],
              "page_size": 1
            }

      - name: Process Response and Get Summary URL
        id: get-summary-url
        if: success()
        run: |
          echo "API Response Content:"
          echo '${{ steps.fetch-notion.outputs.data }}' | jq '.'
          
          url=$(echo '${{ steps.fetch-notion.outputs.data }}' | jq -r '.results[0].properties.URL.url')
          echo "Extracted URL: $url"
          
          if [ -n "$url" ] && [ "$url" != "null" ]; then
            echo "url=$url" >> $GITHUB_OUTPUT
            
            summary_url="${{ secrets.SUMMARY_API }}/$url"
            echo "Summary URL: $summary_url"
            
            redirect_url=$(curl -s -I -o /dev/null -w "%{redirect_url}" "$summary_url")
            echo "Redirected Summary URL: $redirect_url"
            
            if [ -n "$redirect_url" ]; then
              echo "summary_url=$redirect_url" >> $GITHUB_OUTPUT
            else
              echo "Failed to get redirected summary URL"
            fi
          else
            echo "Failed to get a valid URL from Notion response"
            echo "url=" >> $GITHUB_OUTPUT
          fi
