name: Generate Summary

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  fetch-and-generate-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Notion API
        uses: actionsflow/axios@v1
        id: fetch-notion
        with:
          url: https://api.notion.com/v1/databases/${{ secrets.DATABASE_ID }}/query
          method: 'POST'
          accept: 200
          headers: |
            {
              "Authorization": "Bearer ${{ secrets.NOTION_TOKEN }}",
              "Notion-Version": "2022-06-28",
              "Content-Type": "application/json"
            }
          data: |
            {
              "filter": {
                "property": "笔记",
                "url": {
                  "is_empty": true
                }
              },
              "sorts": [
                {
                  "property": "创建时间",
                  "direction": "ascending"
                }
              ],
              "page_size": 5
            }

      - name: Process Response and Update Notion Pages
        if: success()
        run: |
          echo "API Response Content:"
          echo '${{ steps.fetch-notion.outputs.data }}' | jq '.'
          
          results=$(echo '${{ steps.fetch-notion.outputs.data }}' | jq -c '.results[]')
          
          while IFS= read -r result; do
            # Try to get URL from different properties
            url=$(echo "$result" | jq -r '.properties | (.原链接.url // .URL.url // .链接.url // "")')
            page_id=$(echo "$result" | jq -r '.id')
            
            echo "Processing Page ID: $page_id"
            echo "Found URL: $url"
            
            if [ -n "$url" ] && [ "$url" != "null" ]; then
              summary_url="${{ secrets.SUMMARY_API }}/$url"
              echo "Summary URL: $summary_url"
              
              redirect_url=$(curl -s -I -o /dev/null -w "%{redirect_url}" "$summary_url")
              echo "Redirected Summary URL: $redirect_url"
              
              if [ -n "$redirect_url" ]; then
                echo "Updating Notion page with summary URL"
                curl -X PATCH "https://api.notion.com/v1/pages/$page_id" \
                  -H "Authorization: Bearer ${{ secrets.NOTION_TOKEN }}" \
                  -H "Content-Type: application/json" \
                  -H "Notion-Version: 2022-06-28" \
                  -d "{\"properties\":{\"笔记\":{\"url\":\"$redirect_url\"}}}"
                
                echo "Waiting for a period before processing the next record"
                sleep 100
              else
                echo "Failed to get redirected summary URL"
              fi
            else
              echo "Failed to get a valid URL from Notion response"
            fi
          done <<< "$results"
