name: 定时获取

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨2点运行
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch-and-generate-summary:
    runs-on: ubuntu-latest
    steps:
      - name: 发送请求到 Notion API
        uses: actionsflow/axios@v1
        id: fetch-notion
        with:
          url: https://api.notion.com/v1/databases/${{ secrets.DATABASE_ID }}/query
          method: 'POST'
          accept: 200
          headers: '{ "Authorization": "Bearer ${{ secrets.NOTION_TOKEN }}", "Notion-Version": "2022-06-28" }'
          content-type: 'application/json'
          data: '{ "filter": {"property": "Tags", "multi_select": {"contains": ""}}, "sorts": [{"property": "Created", "direction": "descending"}], "page_size": 1 }'

      - name: 处理响应并生成
        if: success()
        run: |
          echo "API 响应内容："
          echo '${{ steps.fetch-notion.outputs.data }}' | jq '.'
          
          url=$(echo '${{ steps.fetch-notion.outputs.data }}' | jq -r '.results[0].properties.URL.url')
          echo "提取的 URL: $url"
          
          if [ -n "$url" ] && [ "$url" != "null" ]; then
            echo "url=$url" >> $GITHUB_OUTPUT
          else
            echo "未能从 Notion 响应中获取有效的 URL"
            exit 1
          fi

      - name: 获取重定向 URL
        if: success()
        uses: actionsflow/axios@v1
        id: get-redirect
        with:
          url: ${{ steps.generate-summary.outputs.url }}
          method: 'GET'
          accept: 200,301,302
          headers: '{ "Authorization": "Bearer ${{ secrets.NOTION_TOKEN }}" }'

      - name: 输出 URL
        if: success()
        run: |
          echo "重定向响应头："
          echo '${{ toJson(steps.get-redirect.outputs.headers) }}'
          
          location_header="${{ fromJson(steps.get-redirect.outputs.headers).location }}"
          if [ -n "$location_header" ]; then
            echo "URL: $location_header"
            echo "redirect_url=$location_header" >> $GITHUB_OUTPUT
          else
            echo "未能获取到重定向 URL"
          fi

      - name: 显示摘要 URL
        if: success() && steps.get-redirect.outputs.redirect_url
        run: |
          echo "摘要 URL: ${{ steps.get-redirect.outputs.redirect_url }}"
