name: Process Notion Pages

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  process-notion-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt

      - name: Fetch Notion Data
        uses: actionsflow/axios@v1
        id: fetch-notion
        with:
          url: https://api.notion.com/v1/databases/${{ secrets.DATABASE_ID }}/query
          method: 'POST'
          headers: |
            {
              "Authorization": "Bearer ${{ secrets.NOTION_TOKEN }}",
              "Notion-Version": "2022-06-28",
              "Content-Type": "application/json"
            }
          data: |
            {
              "filter": {"property": "笔记", "url": {"is_empty": true}},
              "sorts": [{"property": "创建时间", "direction": "ascending"}],
              "page_size": 1
            }

      - name: Process Pages
        if: success()
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          SUMMARY_API: ${{ secrets.SUMMARY_API }}
          IMAGE_API: ${{ secrets.IMAGE_API }}
        run: |
          echo "开始处理Notion页面"
          echo '${{ steps.fetch-notion.outputs.data }}' | jq -c '.results[]' | while read -r result; do
            page_id=$(echo "$result" | jq -r '.id')
            echo "处理页面: $page_id"
            python process.py "$page_id"
          done
          echo "所有页面处理完成"
